-- Phase 1: Database Schema Setup for Parallel Thread-Based Email Architecture
-- Create tables for thread-centric email processing

-- Task 1.1: Create threads table
CREATE TABLE IF NOT EXISTS public.threads (
  thread_id TEXT PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  subject TEXT,
  snippet TEXT,
  last_message_date TIMESTAMPTZ,
  llm_summary JSONB,
  llm_summary_updated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for threads table
CREATE INDEX IF NOT EXISTS idx_threads_user_id ON public.threads(user_id);
CREATE INDEX IF NOT EXISTS idx_threads_last_message_date ON public.threads(last_message_date DESC);

-- Enable Row Level Security for threads
ALTER TABLE public.threads ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for threads
CREATE POLICY "Users can view their own threads" ON public.threads
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own threads" ON public.threads
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own threads" ON public.threads
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own threads" ON public.threads
  FOR DELETE USING (auth.uid() = user_id);

-- Task 1.2: Create thread_messages table
CREATE TABLE IF NOT EXISTS public.thread_messages (
  message_id TEXT PRIMARY KEY,
  thread_id TEXT REFERENCES public.threads(thread_id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  customer_id UUID REFERENCES public.customers(customer_id) ON DELETE SET NULL,
  from_address TEXT,
  to_addresses JSONB,
  cc_addresses JSONB,
  sent_date TIMESTAMPTZ,
  snippet TEXT,
  body_text TEXT,
  body_html TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for thread_messages table
CREATE INDEX IF NOT EXISTS idx_thread_messages_thread_id ON public.thread_messages(thread_id);
CREATE INDEX IF NOT EXISTS idx_thread_messages_user_id ON public.thread_messages(user_id);
CREATE INDEX IF NOT EXISTS idx_thread_messages_customer_id ON public.thread_messages(customer_id);
CREATE INDEX IF NOT EXISTS idx_thread_messages_sent_date ON public.thread_messages(sent_date ASC);

-- Enable Row Level Security for thread_messages
ALTER TABLE public.thread_messages ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for thread_messages
CREATE POLICY "Users can view their own thread messages" ON public.thread_messages
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own thread messages" ON public.thread_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own thread messages" ON public.thread_messages
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own thread messages" ON public.thread_messages
  FOR DELETE USING (auth.uid() = user_id);

-- Task 1.3: Create thread_company_link table
CREATE TABLE IF NOT EXISTS public.thread_company_link (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id TEXT REFERENCES public.threads(thread_id) ON DELETE CASCADE NOT NULL,
  company_id UUID REFERENCES public.companies(company_id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(thread_id, company_id)
);

-- Create indexes for thread_company_link table
CREATE INDEX IF NOT EXISTS idx_thread_company_link_thread_id ON public.thread_company_link(thread_id);
CREATE INDEX IF NOT EXISTS idx_thread_company_link_company_id ON public.thread_company_link(company_id);
CREATE INDEX IF NOT EXISTS idx_thread_company_link_user_id ON public.thread_company_link(user_id);

-- Enable Row Level Security for thread_company_link
ALTER TABLE public.thread_company_link ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for thread_company_link
CREATE POLICY "Users can view their own thread company links" ON public.thread_company_link
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own thread company links" ON public.thread_company_link
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own thread company links" ON public.thread_company_link
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own thread company links" ON public.thread_company_link
  FOR DELETE USING (auth.uid() = user_id);

